name: Flutter

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: flutter pub get

      - name: Set up .env.dev
        run: |
          echo "API_URL=${{ secrets.API_URL }}" >> .env.dev
          echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> .env.dev

      - name: Analyze project source
        run: flutter analyze
        env:
          DART_ANALYSIS_OPTIONS: analysis_options.yaml

      - name: Run tests
        run: flutter test